language: bash

cache:
  pip: true
  directories:
    - $HOME/miniconda3_$TRAVIS_OS_PATH # Add the installation to TRAVIS cache.
    #- $HOME/miniconda3_osx # Add the installation to TRAVIS cache.
    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
    #- $HOME/Library/Caches/Homebrew  # osx local
    #- /usr/local/Homebrew/Library/Caches/Homebrew  # osx main

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt_packages:
          - build-essential
          - git
          - curl
          - libboost-dev


# commands to install dependencies
before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="$HOME/miniconda3_linux/bin:$PATH"

install:
  - bash .travis/travis_install.sh
  - pip --version
  - pip install . --no-deps --upgrade --user
  - export PATH="$HOME/bin:$PATH"

# command to run tests
script:
  - echo $PATH
  - python3 --version
  - build_baited_bloom_filter
    --input-fasta data/transcript.fa
    --kmer 27
    --bloom-size 500M
    --levels 1
    --threads 2
    --output-bloom genome_k27_m500M_l1.bloom
    data/genome.fa.gz
  - find_exons
    --input-fasta data/transcript.fa
    --input-bloom genome_k27_m500M_l1.bloom
    --kmer 27
    --output-fasta test_exons_raw.fa
  # - filter_exons_by_length
  #   --input-fasta test_exons_raw.fa
  #   --minimum-length 27
  #   --trim-left 1
  #   --trim-right 1
  #   --output-fasta test_exons_filtered_by_length.fa
  # - filter_exons_by_extensibility
  #   --input-fasta test_exons_raw.fa
  #   --input-bloom genome_k27_m500M_l1.bloom
  #   --kmer 27
  #   --output-fasta test_exons_filtered_by_extensiblity.fa
