dist: trusty

language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential curl git
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH="/home/travis/miniconda3/bin:$PATH"
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda install abyss bedtools awk

script:
  - abyss-bloom build \
    --kmer=27 \
    --verbose \
    --bloom-size=500M \
    --threads=4 \
    --levels=1 \
    genome_k27_m500M_l1.bloom \
    test/genome.fa.gz
  - python3 exon_finder.py \
    --input-transcriptome test/transcript.fa \
    --input-bloom genome_k27_m500M_l1.bloom \
    --kmer 27
