dist: trusty

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -e ."
# command to run tests
script: python3 setup.py test

script:
  - abyss-bloom build
    --kmer 27
    --threads 4
    --levels 1
    --bloom-size 500M
    --verbose
    genome_k27_m500M_l1.bloom
    test/genome.fa.gz
  - find_exons
    --input-fasta test/transcript.fa
    --input-bloom genome_k27_m500M_l1.bloom
    --kmer 27
    --output-fasta test_exons_raw.fa
  - filter_exons
    --input-fasta test_exons_raw.fa
    --minimum-length 27
    --trim-left 1
    --trim-right 1
    --output-fasta test_exons_filtered.fa
  - paste_exons
    --input-fasta test_exons_filtered.fa
    --gap-size 100
    --output-fasta test_pasted.fa

