language: python3

cache:
  apt: true
  pip: true
  directories:
    - $HOME/miniconda3_$TRAVIS_OS_NAME # Add the installation to TRAVIS cache.
    #- $HOME/miniconda3_osx # Add the installation to TRAVIS cache.
    #- $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
    - $HOME/.bash_profile  # Paths and everything
    #- $HOME/Library/Caches/Homebrew  # osx local
    #- /usr/local/Homebrew/Library/Caches/Homebrew  # osx main
    - /opt

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt_packages:
          - build-essential
          - git
          - curl
          - libboost-dev
          - gcc
          - autoconf
          - bzip2
          - zlib1g
          - libsparsehash-dev
          - cmake

# commands to install dependencies
before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="$HOME/miniconda3_$TRAVIS_OS_NAME/bin:$PATH"
#  - sudo chmod 666 /dev/null  # https://discuss.pivotal.io/hc/en-us/articles/203961428-Unix-server-treats-the-login-with-message-bash-dev-null-Permission-denied-

install:
  - bash .travis/travis_install.sh
  - pip --version
  - pip install . --no-deps --upgrade --user

# command to run tests
script:
  - echo $PATH
  - python3 --version
  - build_baited_bloom_filter
    --input-fasta data/transcript.fa
    --kmer 27
    --bloom-size 500M
    --levels 1
    --threads 2
    --output-bloom genome_k27_m500M_l1.bloom
    data/genome.fa.gz
  - build_splice_graph
    --input-fasta data/transcript.fa
    --input-bloom genome_k27_m500M_l1.bloom
    --kmer 27
    --max-fp-bases 5
    --output-gfa test_exons_raw.gfa
  - gfa1_to_fasta
    --input-gfa test_exons_raw.gfa
    --output-fasta exons.fa
    --soft-mask-overlaps
  - gfa1_to_fasta
    --input-gfa test_exons_raw.gfa
    --output-fasta gapped_transcripts.fa
    --gapped-transcript
    --number-of-ns 100
    --hard-mask-overlaps
  - cat exons.fa

after_failure:
