language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/miniconda3 # Add the installation to TRAVIS cache.

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 3.6
      before:
    - os: osx
      python: 3.6



# commands to install dependencies
before_install:
    - bash .travis/install.sh
    - export PATH="/home/travis/miniconda3/bin:$PATH"
    - conda config --add channels conda-forge
    - conda config --add channels defaults
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda install --yes abyss bedtools biopython

install: "pip install -e ."
# command to run tests
script:
  - python3 setup.py test
  - build_baited_bloom_filter
    --input-fasta data/transcript.fa
    --kmer 27
    --bloom-size 500M
    --levels 1
    --threads 2
    --output-bloom genome_k27_m500M_l1.bloom
    data/genome.fa.gz
  - find_exons
    --input-fasta data/transcript.fa
    --input-bloom genome_k27_m500M_l1.bloom
    --kmer 27
    --output-fasta test_exons_raw.fa
  - filter_exons_by_length
    --input-fasta test_exons_raw.fa
    --minimum-length 27
    --trim-left 1
    --trim-right 1
    --output-fasta test_exons_filtered_by_length.fa
  - filter_exons_by_extensibility
    --input-fasta test_exons_raw.fa
    --input-bloom genome_k27_m500M_l1.bloom
    --kmer 27
    --output-fasta test_exons_filtered_by_extensiblity.fa
