#!/usr/bin/env python3

"""tests.io.transcrtiptome_dicts.py: variables for testing"""

TRANSCRIPTOME_EMPTY_DICT = {}
TRANSCRIPTOME_SIMPLE_DICT = {
    "ENSDART00000161035.1":
        "TGCACGGGTTTATTGTTCACAAAGAGATCGACAATGTGCGCAACTAAAATAAACATAGTACATTTTGATT"
        "ATACACGAACTTAAACTAAAGTCCAATCACACCTCCGCCCCGTTTCCACAGCAGCCTGTCAGGGTGGAGG"
        "AAAAGCGCGGCGGTCATGTGAGGCTCGAGCATCTCTCTCTCTCTCTCTCTCTCTCTCTCTACAGAATGAT"
        "AGAGGGAGCTCGTGAATCACATCATAGTCGTCCTCCCCTCATTCGTCCTCTCCAGCAGACACCGAAAAAC"
        "TGCGTTCATGCCAAAATGGGATGTGGAAATTCCTCCGCCACGAGCACGACAGCCGGAGGTCCTGCAGAGG"
        "TGGCCAAAGATGTGACGGAAGAGCCTTCGCCGGACGACGAGAAGCGGAGGAACTACGGTGGAGTGTATGT"
        "GGGTCTTCCTGCTGATCTGACTGCAGTCGCTGCCAGTCAGTCCAAATCAACACGCAAAGTCAACAGATGT"
        "TTATTGCAGACCTTCAGATAAAACAACATAGAAC"
}
TRANSCRIPTOME_COMPLEX_DICT = {
    "ENSDART00000161035.1":
        "TGCACGGGTTTATTGTTCACAAAGAGATCGACAATGTGCGCAACTAAAATAAACATAGTACATTTTGATT"
        "ATACACGAACTTAAACTAAAGTCCAATCACACCTCCGCCCCGTTTCCACAGCAGCCTGTCAGGGTGGAGG"
        "AAAAGCGCGGCGGTCATGTGAGGCTCGAGCATCTCTCTCTCTCTCTCTCTCTCTCTCTCTACAGAATGAT"
        "AGAGGGAGCTCGTGAATCACATCATAGTCGTCCTCCCCTCATTCGTCCTCTCCAGCAGACACCGAAAAAC"
        "TGCGTTCATGCCAAAATGGGATGTGGAAATTCCTCCGCCACGAGCACGACAGCCGGAGGTCCTGCAGAGG"
        "TGGCCAAAGATGTGACGGAAGAGCCTTCGCCGGACGACGAGAAGCGGAGGAACTACGGTGGAGTGTATGT"
        "GGGTCTTCCTGCTGATCTGACTGCAGTCGCTGCCAGTCAGTCCAAATCAACACGCAAAGTCAACAGATGT"
        "TTATTGCAGACCTTCAGATAAAACAACATAGAAC",
    "ENSDART00000165342.1":
        "AAATATGGAGCTGAAGCCGAGTATCTTGGTATTGGACTGGAACAGAAATCCAGCAAAAACTTTAAGGGAA"
        "ATCACTTTCATTTCATGATCGAAAAACTCCCGCAGATCATAAAAGAGTGGAAGGAAGGACCTGTAGTAGA"
        "AACAAAACTAGGATCTCTGAGAGGTGCCTTCTTGACTGTGAAGGGCAAGGACACAATAGTCAATAGTTAT"
        "CTAGGTGTGCCGTTCGCCAAGCCGCCTGTAGGACCCCTGAGACTTGCTCGACCACAGGCTGCAGAGAAAT"
        "GGCAAGGAGTTAGAGATGCCACCAAACAGCCACGGATGTGCCTCCAGGAAAGGCAAATGACTGTAACTGA"
        "ACTGGAGTTTCTATCGATGGATGTGGAGGTTCCTGAGGTCTCGGAGGATTGCCTGTATCTTAACATCTAC"
        "ACCCCAGTTAAACCTGGACAAGGAGACAAGAAGTTACCAGTCATGGTTTGGATTCATGGTGGAGGACTCT"
        "CTCTTGGATCGGCTTCAATGTATGATGGCTCTGTTCTGGCTGCGTATCAGGATGTGGTCGTGGTGCTCAT"
        "TCAGTACAGATTGGGTCTTCTGGGGTTCTTAAGCACCGGAGACGAGCATGCGCCAGGAAACTATGGTTTT"
        "CTGGATCAAGTAGCTGCCCTTCAGTGGGTTCAGGAGAACATCCACAGCTTCGGTGGAGATCCTGGATCAG"
        "TGACCATCTTTGGAGAGTCTGCTGGAGGAATCAGTGTATCCACGCTGATTCTTTCCCCGCTGGCGTCTGG"
        "ACTGTTTCATCGCGCCATTGCAGAAAGTGGAACTGCCTTCTGGGATGGTTTAGTCATGGCTGATCCTTTT"
        "CAGAGAGCCCAGACTGCAGCCAAACAATGCAACTGTGACAGCAGCAGTTCAGCAAAGATTGTCGACTGCA"
        "TTATGCACTGGTCTGAAGAGGAGGCTCTGGAATGTGCTAAAAAGTTCCAGATGATGCACTTCTCCGTTGC"
        "TGTAGATTCTTATTTCCTTCCCAAACCCATCGAGGAGATTGTTGAGAAACAAGAGTTTAGTAAAGTTCCT"
        "CTCATCAACGGCATTAACAATGATGAGTTTGGCTTCTTGTTGGCTGAATATTTCTTGGGTCCTGAATGGA"
        "TGAATGGGTTGAAAAGAGAGCAAATCGCTGAAGCCTTGACGCTCACATATCCTGATCCCAAGGATCGATG"
        "GATCATTGATCTGGTGGCGAAGGAATATCTGGGCGACACACACGACCCCATTGAAATCCGTGAAGTTTAT"
        "CGGGAGATGATGGGAGACGTGCTGTTTAACATCCCTGCCCTGCAACTGGCAAAACACCACAGCGGCACAG"
        "GAGCTCCAGTGTACCTGTATGAGCTCCAGCATCCGCCCAGCTTCCTCCAGAAGAAGAGGCCTAGCTTCGT"
        "GGGTGTGGACCACGCTGATGACCTCTACTTCATCCAGGGCACCTGCTTCGCTAAAGCCCATCTCAGAATA"
        "AGCGCTCCTTTCACAGAAGAAGAAAACGAGCTCTGCAGGACTGTGATGGCCTACTGGGGGAACTTTGCAC"
        "ACACTGGGTCTCCCAATGGTCCGGGTCTGACACATTGGCCAGAATATGAAAATGAGAATGAGTATCTTGC"
        "CATCGGACTGCAACAGAAACCTGGGAAAAACCTTAAGCACAAACACTATGAGTTCATGACCAAGACTCTT"
        "CCAGAACTCATACGTCAAGGAAAAACCAAGCACTCAGAACTGTAAAAGAAAAAAAAATGACAAGACAATT"
        "AACTGTGATTCAGAATAACAATATTACCATGTAAAGATCAAATAACGACCTTTATTATCACATATATTGA"
        "TGGCAATTTTAAAGATCTTTGACAGAACTTTAGCTGTCAGATTGTATTTTAAAAGAAATAACTAATGTTA"
        "TGCACTGAAAAATAAAAGTCGGACACCTT"
}
