#!/usr/bin/env python3

"""Unittests for exfi.io.fasta_to_dict"""

from unittest import \
    TestCase, \
    main

from exfi.io.fasta_to_dict import \
    fasta_to_dict

from exfi.classes import FastaDict

from tests.custom_assertions import \
    CustomAssertions

EXONS_EMPTY_FN = "tests/io/exons_empty.fa"
EXONS_SIMPLE_FN = "tests/io/exons_simple.fa"
EXONS_COMPLEX_FN = "tests/io/exons_complex.fa"
EXONS_SPACED_FN = "tests/io/spaced.fa"
EXONS_TABBED_FN = "tests/io/tabbed.fa"

EXONS_EMPTY_DICT = FastaDict()
EXONS_SIMPLE_DICT = FastaDict({
    'ENSDART00000161035.1:0-326':
        'TGCACGGGTTTATTGTTCACAAAGAGATCGACAATGTGCGCAACTAAAATAAACATAGTACATTTTGATTATACACGAACTTAAACTAAA'
        'GTCCAATCACACCTCCGCCCCGTTTCCACAGCAGCCTGTCAGGGTGGAGGAAAAGCGCGGCGGTCATGTGAGGCTCGAGCATCTCTCTCT'
        'CTCTCTCTCTCTCTCTCTCTACAGAATGATAGAGGGAGCTCGTGAATCACATCATAGTCGTCCTCCCCTCATTCGTCCTCTCCAGCAGAC'
        'ACCGAAAAACTGCGTTCATGCCAAAATGGGATGTGGAAATTCCTCCGCCACGAGCA'
})
EXONS_COMPLEX_DICT = FastaDict({
    'ENSDART00000161035.1:0-326':
        'TGCACGGGTTTATTGTTCACAAAGAGATCGACAATGTGCGCAACTAAAATAAACATAGTACATTTTGATTATACACGAACTTAAACTAAA'
        'GTCCAATCACACCTCCGCCCCGTTTCCACAGCAGCCTGTCAGGGTGGAGGAAAAGCGCGGCGGTCATGTGAGGCTCGAGCATCTCTCTCT'
        'CTCTCTCTCTCTCTCTCTCTACAGAATGATAGAGGGAGCTCGTGAATCACATCATAGTCGTCCTCCCCTCATTCGTCCTCTCCAGCAGAC'
        'ACCGAAAAACTGCGTTCATGCCAAAATGGGATGTGGAAATTCCTCCGCCACGAGCA',
    'ENSDART00000161035.1:397-472':
        'AGGAACTACGGTGGAGTGTATGTGGGTCTTCCTGCTGATCTGACTGCAGTCGCTGCCAGTCAGTCCAAATCAACA',
    'ENSDART00000161035.1:477-523':
        'AGTCAACAGATGTTTATTGCAGACCTTCAGATAAAACAACATAGAA',
    'ENSDART00000165342.1:5-127':
        'TGGAGCTGAAGCCGAGTATCTTGGTATTGGACTGGAACAGAAATCCAGCAAAAACTTTAAGGGAAATCACTTTCATTTCATGATCGAAAA'
        'ACTCCCGCAGATCATAAAAGAGTGGAAGGAAG',
    'ENSDART00000165342.1:125-304':
        'AGGACCTGTAGTAGAAACAAAACTAGGATCTCTGAGAGGTGCCTTCTTGACTGTGAAGGGCAAGGACACAATAGTCAATAGTTATCTAGG'
        'TGTGCCGTTCGCCAAGCCGCCTGTAGGACCCCTGAGACTTGCTCGACCACAGGCTGCAGAGAAATGGCAAGGAGTTAGAGATGCCACCA',
    'ENSDART00000165342.1:317-460':
        'GTGCCTCCAGGAAAGGCAAATGACTGTAACTGAACTGGAGTTTCTATCGATGGATGTGGAGGTTCCTGAGGTCTCGGAGGATTGCCTGTA'
        'TCTTAACATCTACACCCCAGTTAAACCTGGACAAGGAGACAAGAAGTTACCAG',
    'ENSDART00000165342.1:459-592':
        'GTCATGGTTTGGATTCATGGTGGAGGACTCTCTCTTGGATCGGCTTCAATGTATGATGGCTCTGTTCTGGCTGCGTATCAGGATGTGGTC'
        'GTGGTGCTCATTCAGTACAGATTGGGTCTTCTGGGGTTCTTAA',
    'ENSDART00000165342.1:591-650':
        'AGCACCGGAGACGAGCATGCGCCAGGAAACTATGGTTTTCTGGATCAAGTAGCTGCCCT',
    'ENSDART00000165342.1:645-746':
        'GCCCTTCAGTGGGTTCAGGAGAACATCCACAGCTTCGGTGGAGATCCTGGATCAGTGACCATCTTTGGAGAGTCTGCTGGAGGAATCAGT'
        'GTATCCACGCT',
    'ENSDART00000165342.1:746-851':
        'GATTCTTTCCCCGCTGGCGTCTGGACTGTTTCATCGCGCCATTGCAGAAAGTGGAACTGCCTTCTGGGATGGTTTAGTCATGGCTGATCC'
        'TTTTCAGAGAGCCCA',
    'ENSDART00000165342.1:854-886':
        'TGCAGCCAAACAATGCAACTGTGACAGCAGCA',
    'ENSDART00000165342.1:899-953':
        'TGTCGACTGCATTATGCACTGGTCTGAAGAGGAGGCTCTGGAATGTGCTAAAAA',
    'ENSDART00000165342.1:974-1097':
        'CGTTGCTGTAGATTCTTATTTCCTTCCCAAACCCATCGAGGAGATTGTTGAGAAACAAGAGTTTAGTAAAGTTCCTCTCATCAACGGCAT'
        'TAACAATGATGAGTTTGGCTTCTTGTTGGCTGA',
    'ENSDART00000165342.1:1098-1175':
        'TATTTCTTGGGTCCTGAATGGATGAATGGGTTGAAAAGAGAGCAAATCGCTGAAGCCTTGACGCTCACATATCCTGA',
    'ENSDART00000165342.1:1176-1324':
        'CCCAAGGATCGATGGATCATTGATCTGGTGGCGAAGGAATATCTGGGCGACACACACGACCCCATTGAAATCCGTGAAGTTTATCGGGAG'
        'ATGATGGGAGACGTGCTGTTTAACATCCCTGCCCTGCAACTGGCAAAACACCACAGCG'
})


class TestFastaToDict(TestCase, CustomAssertions):
    """Tests for fasta_to_dict"""

    def test_empty(self):
        """exfi.io.fasta_to_dict: process an empty fasta"""
        actual = fasta_to_dict(EXONS_EMPTY_FN)
        expected = EXONS_EMPTY_DICT
        self.assertEqualDict(actual, expected)

    def test_simple(self):
        """exfi.io.fasta_to_dict: process a simple fasta"""
        actual = fasta_to_dict(EXONS_SIMPLE_FN)
        expected = EXONS_SIMPLE_DICT
        self.assertEqualDict(actual, expected)

    def test_complex(self):
        """exfi.io.fasta_to_dict: process a complex fasta"""
        actual = fasta_to_dict(EXONS_COMPLEX_FN)
        expected = EXONS_COMPLEX_DICT
        self.assertEqualDict(actual, expected)

    def test_spaced(self):
        """exfi.io.fasta_to_dict: process a fasta with spaces in the header"""
        actual = fasta_to_dict(EXONS_SPACED_FN)
        expected = EXONS_COMPLEX_DICT
        self.assertEqualDict(actual, expected)

    def test_tabbed(self):
        """exfi.io.fasta_to_dict: process a fasta with tabs in the header"""
        actual = fasta_to_dict(EXONS_TABBED_FN)
        expected = EXONS_COMPLEX_DICT
        self.assertEqualDict(actual, expected)

if __name__ == '__main__':
    main()
